### ISSUE TITLE
motion fails to build on Ubuntu with ffmpeg 7.1

### ISSUE THREAD

**Issue by axeljerabek** [Motion-Project/motion#1868]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

5.2.x

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Ubuntu

### Disto version number

24.04.2LTS

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

movie.cpp: In member function ‘int cls_movie::set_quality()’:
movie.cpp:305:34: error: ‘FF_PROFILE_H264_HIGH’ was not declared in this scope; did you mean ‘AV_PROFILE_H264_HIGH’?
  305 |             ctx_codec->profile = FF_PROFILE_H264_HIGH;
      |                                  ^~~~~~~~~~~~~~~~~~~~
      |                                  AV_PROFILE_H264_HIGH
make[2]: *** [Makefile:510: movie.o] Fehler 1
make[2]: Verzeichnis „/home/axel/dev/motion/src“ wird verlassen
make[1]: *** [Makefile:597: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/axel/dev/motion“ wird verlassen
make: *** [Makefile:418: all] Fehler 2
Making install in src
make[1]: Verzeichnis „/home/axel/dev/motion/src“ wird betreten
depbase=`echo movie.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I..  -Dconfigdir=\"/usr/local/var/lib/motion\" -Dsysconfdir=\"/usr/local/etc/motion\" -DLOCALEDIR=\"/usr/local/share/locale\" -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -I/usr/local/include  -I/usr/include/webp  -I/usr/include/libcamera  -I/usr/include/x86_64-linux-gnu  -I/usr/local/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT    -W -O3 -Wall -Wextra -Wconversion -Wformat -Wshadow -Wpointer-arith -Wwrite-strings -Wredundant-decls -Wno-sign-conversion -Wno-sign-compare -ggdb -g3   -std=c++17 -MT movie.o -MD -MP -MF $depbase.Tpo -c -o movie.o movie.cpp &&\
mv -f $depbase.Tpo $depbase.Po
movie.cpp: In member function ‘int cls_movie::set_quality()’:
movie.cpp:305:34: error: ‘FF_PROFILE_H264_HIGH’ was not declared in this scope; did you mean ‘AV_PROFILE_H264_HIGH’?
  305 |             ctx_codec->profile = FF_PROFILE_H264_HIGH;
      |                                  ^~~~~~~~~~~~~~~~~~~~
      |                                  AV_PROFILE_H264_HIGH
make[1]: *** [Makefile:510: movie.o] Fehler 1
make[1]: Verzeichnis „/home/axel/dev/motion/src“ wird verlassen
make: *** [Makefile:597: install-recursive] Fehler 1

### Relevant Motion log output (at log_level 8)

```shell
none
```

**Comment by axeljerabek** [comment]
Temp fixed it by switching FF_PROFILE_H264_HIGH to AV_PROFILE_H264_HIGH in src/movie.cpp
