### ISSUE TITLE
MySQL 8.0.1 removes support for the `my_bool` datatype

### ISSUE THREAD

**Issue by vilhelmgray** [Motion-Project/motion#995]
This issue only affects MySQL; MariaDB will continue to support `my_bool`.

The following build error occurs when attempting to compile with MySQL 8.0.1:
```
motion.c: In function ‘motion_init’:
motion.c:1146:13: error: unknown type name ‘my_bool’; did you mean ‘bool’?
 1146 |             my_bool my_true = TRUE;
      |             ^~~~~~~
      |             bool
make: *** [Makefile:105: motion.o] Error 1
make: *** Waiting for unfinished jobs....
```

Noted in 8.0.1 changelog (https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling):

The **mysql.h** header file now requires a C++ or C99 compiler to
compile.

The `my_bool` type is no longer used in MySQL source code. Any third-party code that used this type to represent C boolean variables should use the bool or int C type instead.

**Comment by tosiara** [comment]
Which OS is delivering this version of MySQL?

**Comment by vilhelmgray** [comment]
This was reported to me for the Motion Gentoo package: https://bugs.gentoo.org/692682
Here's the main MySQL bug page for Gentoo: https://bugs.gentoo.org/692570

I haven't tested other distros yet, but perhaps someone can verify for these other distros. The latest Ubuntu may be affected by this if it's on MySQL version 8.0.16: https://packages.ubuntu.com/eoan/mysql-server

Regardless, this change is coming from the upstream MySQL project, so a Motion user will encounter this issue if they try to use the vanilla MySQL tarball from the MySQL site.
