### PR TITLE
mysql my_bool value

### LINKED ISSUE #995: MySQL 8.0.1 removes support for the `my_bool` datatype
This issue only affects MySQL; MariaDB will continue to support `my_bool`.

The following build error occurs when attempting to compile with MySQL 8.0.1:
```
motion.c: In function ‘motion_init’:
motion.c:1146:13: error: unknown type name ‘my_bool’; did you mean ‘bool’?
 1146 |             my_bool my_true = TRUE;
      |             ^~~~~~~
      |             bool
make: *** [Makefile:105: motion.o] Error 1
make: *** Waiting for unfinished jobs....
```

Noted in 8.0.1 changelog (https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling):

The **mysql.h** header file now requires a C++ or C99 compiler to
compile.

The `my_bool` type is no longer used in MySQL source code. Any third-party code that used this type to represent C boolean variables should use the bool or int C type instead.

### PR DESCRIPTION
**Pull request by Mr-DaveDev**
Revise `my_bool` type to `int`

Closes #995

### CODE REVIEW

**Comment by AdamMiltonBarker** [comment]
@Mr-DaveDev  thanks for this, it pointed to me to the fix for the same issue in mosquitto-auth-plug. Through a search I found It had come up in https://github.com/jpmens/mosquitto-auth-plug/issues/282 but was unanswered, linking the issue in case anyone else gets the same.
