### ISSUE TITLE
Doesn't compile with ffmpeg 4.0

### ISSUE THREAD

**Issue by ilgiznurgaliev** [Motion-Project/motion#710]
Hi,

I'm getting the folowing errors when trying to compile motion v4.1.1 with ffmpeg 4.0:

`ffmpeg.c: In function 'ffmpeg_set_quality':
ffmpeg.c:541:41: error: 'CODEC_FLAG_QSCALE' undeclared (first use in this function)
             ffmpeg->ctx_codec->flags |= CODEC_FLAG_QSCALE;
                                         ^
`

`ffmpeg.c:541:41: note: each undeclared identifier is reported only once for each function it appears in
ffmpeg.c: In function 'ffmpeg_set_codec':
ffmpeg.c:666:33: error: 'CODEC_FLAG_GLOBAL_HEADER' undeclared (first use in this function)
     ffmpeg->ctx_codec->flags |= CODEC_FLAG_GLOBAL_HEADER;
                                 ^
`

0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: compiled from source
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Centos 7.4 (3.10.0-693.21.1.el7.x86_64)

Thanks. Casper.

**Comment by ilgiznurgaliev** [comment]
Compiled successfully with latest git version: 4.1.1+git00d3b25.

**Comment by rotrials** [comment]
@ilgiznurgaliev what do you mean by +git00d3b25 ?

**Comment by tosiara** [comment]
00d3b25 is a revision ID
https://github.com/Motion-Project/motion/tree/00d3b25d959245859f1ae18af2d8e6beb31f151c
The current latest master is 503af40
